# Generated by Django 3.1.7 on 2021-03-11 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='duration_subscription',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_subscription',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
