version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - migration
      
  db:
    image: postgres:10.5
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ./.env.db


    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  migration:
    build: .
    env_file:
      - ./.env.dev
    image: app
    command: python manage.py migrate
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - w8p7