version: "3.8"
services:
  web:

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db
      
  db:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=myuserpassword
      - POSTGRES_DB=mydb
    ports:
      - "5433:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
