# Generated by Django 3.1.7 on 2021-03-11 19:39

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('is_important', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'tag',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('l', 'Limited'), ('p', 'Public')], default='l', max_length=1)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('hints', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None)),
                ('votes', models.PositiveSmallIntegerField(default=0)),
                ('answer', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_query_name='tags', to='api.Category')),
            ],
            options={
                'ordering': ('votes',),
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('visibility', models.CharField(choices=[('l', 'Limited'), ('p', 'Public')], default='l', max_length=1)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish'), ('r', 'Removed')], default='p', max_length=1)),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/blog', verbose_name='blog thumbnail')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'blog post',
            },
        ),
    ]
