# Generated by Django 3.1.7 on 2021-09-01 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210901_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionvote',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userquestionvote',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserExamVote',
        ),
        migrations.DeleteModel(
            name='UserQuestionVote',
        ),
    ]
