# Generated by Django 3.1.7 on 2021-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210901_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='questionset',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
