# Generated by Django 3.2.7 on 2021-09-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210901_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
        migrations.AlterField(
            model_name='questionset',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='questions', to='api.Question'),
        ),
    ]
