# Generated by Django 3.2.7 on 2021-09-01 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20210901_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='likes',
            field=models.ManyToManyField(related_name='setlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
